### PR TITLE
Use tsc and target ESM only

### PR DESCRIPTION
**Pull request by jcbhmr**
This is a BREAKING CHANGE and would necessitate a version bump.

This PR would...
- [x] Use tsc instead of rollup
- [x] ELIMINATE the dual package hazard #37
- [x] Re-build the dist folder

### CODE REVIEW

**Comment by mesqueeb** [comment]
I do like the notion of this PR seeing how much _less_ setup the build step has. It's way cleaner in many ways than what I currently have.

However, before I can merge this i'll need to try and publish a beta version on NPM and double check against https://arethetypeswrong.github.io/?p=is-what If the types are correct then I'd be happy to implement this PR and major upgrade is-what to require node v16.

PS: a reason that I love having the dist folder in the git repo for small util packages like these is that it's really clear to see the exact changes that a build step change brings. That's the reason, and I believe another reason was for DENO, but it's been so long I can't remember fully.

**Comment by jcbhmr** [comment]
> it's really clear to see the exact changes that a build step change brings.

Ideally you wouldn't have to care at all! 🤣 I think that GitHub Actions Artifacts are great for this. You can `npm pack` and upload the .tag.gz for each commit and BOOM! 💥 you can see _everything_ that you'd ever want as a little preview! But that's overkill in most cases since you can just click this:

image

and open in Codespaces in about 20s 😉

But Ido understand that you like co-locating build and source code. A good compromise might be the Artifact thing or some kind of "bundle size checker" or similar?

**Comment by jcbhmr** [comment]
@mesqueeb You can use `npm pack` .tar.gz output: 
image

image

Looks good! 👍 Targetting ESM only means Node.js v12+. Node.js LTS is 16 which Ends in 3 months and 1 week (11 Sep 2023) https://endoflife.date/nodejs

**Comment by jcbhmr** [comment]
Closing in favor of stacking a PR on top of #74

**Pull request closed without merging**
