### PR TITLE
Use `tsc`

### PR DESCRIPTION
**Pull request by jcbhmr**
This PR would...
- [x] Not solve the #37
- [x] Keep CJS and ESM builds
- [x] Remove rollup
- [x] Use tsc!

This is intended to be a non-breaking migration from rollup to tsc. Later #55 can be considered with the move to ESM-only

THIS DOES NOT SOLVE THE DUAL PACKAGE HAZARD ISSUE!

### CODE REVIEW

**Comment by jcbhmr** [comment]
There's an open issue on typescript github to support changing file extensions at tsc buildtime. That hasn't been encouraged since it's mostly used to cause the not-so-great dual package hazard. Instead TS team _seems_ to recommend that you just build an ESM or CJS and then wrap it in another .mjs or .cjs file as a facade for the other module system. https://github.com/microsoft/TypeScript/issues/49462

**Comment by jcbhmr** [comment]
You'll note that I used a tricksy hack to make the cjs folder treat .js as .cjs by putting a `{"type":"commonjs"}` package.json in there 😆

**Comment by jcbhmr** [comment]
@mesqueeb This is the next PR that I think should be tackled 😊

**Comment by mesqueeb** [comment]
closing in favour of https://github.com/mesqueeb/is-what/pull/87

**Pull request closed without merging**
